package com.example.myarena.tests;

import com.example.myarena.domain.Terrain;
import com.example.myarena.domain.TerrainType;
import com.example.myarena.services.TerrainManager;
import com.example.myarena.util.DatabaseConfig;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.MethodName.class)
public class TerrainUseCaseTest {

    private TerrainManager terrainManager;

    private static final Long testOwnerId = 999L;
    private static final String testTerrainName = "TEST_TERRAIN_UC";
    private static Long testTerrainId;

    @BeforeAll
    static void cleanupBefore() {
        System.out.println("=== TERRAIN TEST SETUP ===");

        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement()) {

            // Clean previous test terrains
            stmt.executeUpdate("DELETE FROM terrains WHERE name LIKE '" + testTerrainName + "%'");

            // Ensure owner exists (FK safety if owner_id is used)
            String createOwnerSql =
                    "INSERT INTO users (id, name, email, password_hash, phone, role, status) " +
                            "VALUES (" + testOwnerId + ", 'Test Owner', 'terrain_owner@test.com', 'hash123', '00000000', 'OWNER', 'ACTIVE') " +
                            "ON CONFLICT (id) DO NOTHING";
            stmt.executeUpdate(createOwnerSql);

            System.out.println("✓ Database cleaned & Owner ensured");

        } catch (Exception e) {
            System.err.println("⚠ Setup warning: " + e.getMessage());
        }
    }

    @BeforeEach
    void setUp() {
        terrainManager = new TerrainManager();
    }

    @Test
    @DisplayName("UC1 - Create Terrain")
    void test01CreateTerrain() {
        Terrain t = new Terrain();
        t.setName(testTerrainName + "_1");
        t.setType(TerrainType.FOOTBALL);
        t.setDescription("JUnit use-case terrain");
        t.setLocation("Test Location");
        t.setPricePerHour(50);
        t.setCapacity(22);
        t.setAvailable(true);

        // si tu as ownerId dans ta table, tu peux le mettre (sinon ignore)
        try { t.setOwnerId(testOwnerId); } catch (Exception ignored) {}

        Terrain created = terrainManager.createTerrain(t);

        assertNotNull(created, "Terrain should be created");
        assertNotNull(created.getId(), "Terrain ID should be generated by DB");
        testTerrainId = created.getId();

        System.out.println("✓ Terrain Created: ID " + testTerrainId);
    }

    @Test
    @DisplayName("UC2 - Verify Terrain Persistence")
    void test02VerifyPersistence() {
        assertNotNull(testTerrainId, "Previous test did not create terrain, cannot verify persistence");

        List<Terrain> all = terrainManager.getAllTerrains();
        assertNotNull(all);

        Terrain found = all.stream()
                .filter(t -> testTerrainId.equals(t.getId()))
                .findFirst()
                .orElse(null);

        assertNotNull(found, "Created terrain should be retrievable");
        assertTrue(found.getName().startsWith(testTerrainName), "Name should match test prefix");
        assertEquals(50, found.getPricePerHour(), 0.01);
        System.out.println("✓ Terrain Found in list");
    }

    @Test
    @DisplayName("UC3 - Update Terrain")
    void test03UpdateTerrain() {
        assertNotNull(testTerrainId);

        // On récupère via SQL pour être sûr de l'objet actuel (comme tes collègues)
        Terrain t = null;
        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM terrains WHERE id = " + testTerrainId)) {

            if (rs.next()) {
                t = new Terrain();
                t.setId(rs.getLong("id"));
                t.setName(rs.getString("name"));
                String type = rs.getString("type");
                if (type != null) t.setType(TerrainType.valueOf(type));
                t.setDescription(rs.getString("description"));
                t.setLocation(rs.getString("location"));
                t.setPricePerHour(rs.getDouble("price_per_hour"));
                t.setCapacity(rs.getInt("capacity"));
                t.setAvailable(rs.getBoolean("available"));
            }
        } catch (Exception e) {
            fail("DB read failed: " + e.getMessage());
        }

        assertNotNull(t);

        t.setPricePerHour(79.99);
        t.setCapacity(30);
        t.setName(testTerrainName + "_UPDATED");

        Terrain updated = terrainManager.updateTerrain(t);

        assertNotNull(updated);
        assertEquals(testTerrainId, updated.getId());
        System.out.println("✓ Terrain Updated");
    }

    @Test
    @DisplayName("UC4 - Delete Terrain")
    void test04DeleteTerrain() {
        assertNotNull(testTerrainId);

        terrainManager.deleteTerrain(testTerrainId);

        // verify via SQL
        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT id FROM terrains WHERE id = " + testTerrainId)) {

            assertFalse(rs.next(), "Terrain should be deleted from DB");
            System.out.println("✓ Terrain Deleted");
        } catch (Exception e) {
            fail("DB verification failed: " + e.getMessage());
        }
    }

    @AfterAll
    static void cleanupAfter() {
        System.out.println("=== TERRAIN TEST CLEANUP ===");
        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("DELETE FROM terrains WHERE name LIKE '" + testTerrainName + "%'");
            System.out.println("✓ Cleanup done");
        } catch (Exception e) {
            System.err.println("⚠ Cleanup warning: " + e.getMessage());
        }
    }
}
